pipeline:
  build:
    image: karappo/dronedeploy:drone-0.8
    # pull: true
    environment:
      - DEP_MASTER_COMMAND=rsync
      - DEP_MASTER_HOST=karappojp.sakura.ne.jp
      - DEP_MASTER_USER=karappojp
      - DEP_MASTER_HOST_DIR=/home/karappojp/www/preview/ycam.karappo.jp
      - DEP_MASTER_INCLUDE_FILE=https://raw.githubusercontent.com/karappo/drone-deploy/drone-compatible/v0.8/include-files/php/.depinc.sh
    commands:
      - echo "$SSH_KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
      - curl https://raw.githubusercontent.com/karappo/drone-deploy/drone-compatible/v0.8/deploy.sh | bash
    secrets: [ ssh_key ]
  notify:
    image: plugins/slack
    channel: builds-karappo
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]
